export class States{
    static getStates(): Array<any>{
        return [
            //#region statelist
               { val: "", name: "Select One" },
                 { val: "AK", name: "Alaska" },
                 { val: "AL", name: "Alabama" },
                 { val: "AR", name: "Arkansas" },
                 { val: "AZ", name: "Arizona" },
                 { val: "CA", name: "California" },
                 { val: "CO", name: "Colorado" },
                 { val: "CT", name: "Connecticut" },
                 { val: "DC", name: "District of Columbia" },
                 { val: "DE", name: "Delaware" },
                 { val: "FL", name: "Florida" },
                 { val: "GA", name: "Georgia" },
                 { val: "HI", name: "Hawaii" },
                 { val: "IA", name: "Iowa" },
                 { val: "ID", name: "Idaho" },
                 { val: "IL", name: "Illinois" },
                 { val: "IN", name: "Indiana" },
                 { val: "KS", name: "Kansas" },
                 { val: "KY", name: "Kentucky" },
                 { val: "LA", name: "Louisiana" },
                 { val: "MA", name: "Massachusetts" },
                 { val: "MD", name: "Maryland" },
                 { val: "ME", name: "Maine" },
                 { val: "MI", name: "Michigan" },
                 { val: "MN", name: "Minnesota" },
                 { val: "MO", name: "Missouri" },
                 { val: "MS", name: "Mississippi" },
                 { val: "MT", name: "Montana" },
                 { val: "NC", name: "North Carolina" },
                 { val: "ND", name: "North Dakota" },
                 { val: "NE", name: "Nebraska" },
                 { val: "NH", name: "New Hampshire" },
                 { val: "NJ", name: "New Jersey" },
                 { val: "NM", name: "New Mexico" },
                 { val: "NV", name: "Nevada" },
                 { val: "NY", name: "New York" },
                 { val: "OH", name: "Ohio" },
                 { val: "OK", name: "Oklahoma" },
                 { val: "OR", name: "Oregon" },
                 { val: "PA", name: "Pennsylvania" },
                 { val: "PR", name: "Puerto Rico" },
                 { val: "RI", name: "Rhode Island" },
                 { val: "SC", name: "South Carolina" },
                 { val: "SD", name: "South Dakota" },
                 { val: "TN", name: "Tennessee" },
                 { val: "TX", name: "Texas" },
                 { val: "UT", name: "Utah" },
                 { val: "VA", name: "Virginia" },
                 { val: "VT", name: "Vermont" },
                 { val: "WA", name: "Washington" },
                 { val: "WI", name: "Wisconsin" },
                 { val: "WV", name: "West Virginia" },
                 { val: "WY", name: "Wyoming" },
                 { val: "AB", name: "Alberta" },
                 { val: "BC", name: "British Columbia" },
                 { val: "MB", name: "Manitoba" },
                 { val: "NB", name: "New Brunswick" },
                 { val: "NF", name: "Newfoundland" },
                 { val: "NT", name: "Northwest Territories" },
                 { val: "NS", name: "Nova Scotia" },
                 { val: "NU", name: "Nunavut" },
                 { val: "ON", name: "Ontario"},
                 { val: "PE", name: "Prince Edward Island" },
                 { val: "QC", name: "Quebec" },
                 { val: "SK", name: "Saskatchewan" },
                 { val: "YT", name: "Yukon Territory" }];
    }
}